[workspace]
members = [
    "chs",
    "chs_lexer",
    "chs_ast",
    "chs_types",
    "chs_util", "chs_ir",
]
resolver = "2"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true
