[package]
name = "chsvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
