[workspace]
members = ["chs", "chs_ast", "chs_compiler", "chs_lexer", "chs_types", "chs_util", "chsvm"]
resolver = "2"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true
