[workspace]
members = [
    "chsc",
    "test_maker",
    "chslexer",
]
resolver = "2"

package.version = "0.1.0"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "2.0.12"
