[package]
name = "chs_ir"
version = "0.1.0"
edition = "2021"

[dependencies]
chs_util = {path = "../chs_util"}
chs_ast  = {path = "../chs_ast"}
chs_lexer  = {path = "../chs_lexer"}
chs_types = {path = "../chs_types"}
