[package]
name = "chs"
version = "0.1.0"
edition = "2021"

[dependencies]
chs_lexer = { path = "../chs_lexer/" }
chs_ast = { path = "../chs_ast/" }
chs_util = { path = "../chs_util/" }
chs_codegen = {path = "../chs_codegen"}
