name: TestMaker CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: stevenwdv/setup-fasm@v1.4.4
    - name: Run on test
      run: cargo run --bin test_maker -- -p
    - name: Run on euler
      run: cargo run --bin test_maker -- --test-folder euler -p
